

name: Install GCloud
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy App Engine
    steps:
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
