# .github/workflows/test.yml
name: Deploy to TEST
on:
  push:
    branches:
      - dev
env:
  PROJECT_ID: ${{ secrets.GCP_TEST_PROJECT_ID }}
  RUN_REGION: us-east1
  SA_KEY_JSON: ${{ secrets.GCP_TEST_SA_KEY_JSON }}
jobs:
  deploy:
    name: Deploy to TEST
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - id: 'auth'
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with: 
          credentials_json: '${{ secrets.GCP_TEST_SA_KEY_JSON }}'

      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_TEST_PROJECT_ID }}

      - name: Use gcloud CLI to deploy to TEST
        run: gcloud app deploy --quiet

      - name: Use gcloud CLI to deploy cron jobs to TEST
        run: gcloud app deploy cron.yaml --quiet
